/* Generated by bvh-codegen. DO NOT EDIT. */
/*
 * MIT License
 *
 * Copyright (c) 2026-present K. S. Ernest (iFire) Lee
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */
#ifndef PREDICTIVE_BVH_H
#define PREDICTIVE_BVH_H

#include <stdint.h>
#include <stdbool.h>
#include <math.h>
#include "thirdparty/misc/r128.h"

#ifdef _MSC_VER
#include <intrin.h>
static inline uint32_t _pbvh_clz(uint32_t x) {
    unsigned long idx;
    _BitScanReverse(&idx, x);
    return 31 - (uint32_t)idx;
}
#else
#define _pbvh_clz(x) ((uint32_t)__builtin_clz(x))
#endif

/* r128.h provides: R128_one = {0,1} (1.0 in 64.64), R128_min, R128_max. */
static const R128 _r128_zero = { 0, 0 };
#define R128_ZERO _r128_zero
#define R128_ONE  R128_one

static inline R128 r128_from_int(int64_t v) {
    R128 r; r128FromInt(&r, v); return r;
}
static inline R128 r128_neg(R128 a) {
    R128 r; r128Neg(&r, &a); return r;
}
static inline R128 r128_add(R128 a, R128 b) {
    R128 r; r128Add(&r, &a, &b); return r;
}
static inline R128 r128_sub(R128 a, R128 b) {
    R128 r; r128Sub(&r, &a, &b); return r;
}
static inline R128 r128_mul(R128 a, R128 b) {
    R128 r; r128Mul(&r, &a, &b); return r;
}
static inline R128 r128_div(R128 a, R128 b) {
    R128 r; r128Div(&r, &a, &b); return r;
}
static inline int64_t r128_to_int(R128 a) {
    return (int64_t)a.hi;  /* truncate fractional part */
}
static inline int r128_le(R128 a, R128 b) {
    return r128Cmp(&a, &b) <= 0;
}
static inline int r128_eq(R128 a, R128 b) {
    return a.lo == b.lo && a.hi == b.hi;
}

static inline R128 pow_int_r128(R128 base, int exp) {
    R128 r = R128_ONE, b = base;
    while (exp > 0) {
        if (exp & 1) r = r128_mul(r, b);
        b = r128_mul(b, b);
        exp >>= 1;
    }
    return r;
}

/* Float→R128 (preserves fractional bits via double intermediate) */
static inline R128 r128_from_float(float f) {
    double d = (double)f;
    R128 r;
    r.hi = (int64_t)d;
    r.lo = (uint64_t)((d - (double)r.hi) * 18446744073709551616.0);
    return r;
}
/* Unsigned 32-bit → R128 */
static inline R128 r128_from_u32(uint32_t v) {
    R128 r; r.hi = (int64_t)v; r.lo = 0; return r;
}
/* R128 → float */
static inline float r128_to_float(R128 a) {
    return (float)a.hi + (float)a.lo * 5.421010862427522e-20f; /* 2^-64 */
}

/* ══════════════════════════════════════════════════════════════════════════
   PROVED SPATIAL PRIMITIVES (R128 polynomial + direct C translation)
   ══════════════════════════════════════════════════════════════════════════ */

/* Ghost expansion v*d + a_half*d^2. Proved: expansion_covers_k_ticks */
template <typename T>
static inline T ghost_bound(T v, T a_half, T ticks_ahead) {
    T t0 = (v * ticks_ahead);
    T t1 = (a_half * ticks_ahead);
    T t2 = (t1 * ticks_ahead);
    T t3 = (t0 + t2);
    return t3;
}

/* Surface area 2(wh+hd+wd). Proved: surfaceArea_nonneg */
template <typename T>
static inline T surface_area(T w, T h, T d) {
    T t0 = (w * h);
    T t1 = (h * d);
    T t2 = (t0 + t1);
    T t3 = (w * d);
    T t4 = (t2 + t3);
    T t5 = (T(2) * t4);
    return t5;
}

/* Ghost AABB min bound per axis. Proved: expansion_covers_k_ticks */
template <typename T>
static inline T ghost_aabb_min(T center, T ext, T v, T a_half, T tau) {
    T t0 = (T(-1) * ext);
    T t1 = (center + t0);
    T t2 = (v * tau);
    T t3 = (a_half * tau);
    T t4 = (t3 * tau);
    T t5 = (t2 + t4);
    T t6 = (T(-1) * t5);
    T t7 = (t1 + t6);
    return t7;
}

/* Ghost AABB max bound per axis. Proved: expansion_covers_k_ticks */
template <typename T>
static inline T ghost_aabb_max(T center, T ext, T v, T a_half, T tau) {
    T t0 = (center + ext);
    T t1 = (v * tau);
    T t2 = (a_half * tau);
    T t3 = (t2 * tau);
    T t4 = (t1 + t3);
    T t5 = (t0 + t4);
    return t5;
}

/* Plane corner valuation: nx*x + ny*y + nz*z + d.
   Pure ring polynomial, EGraph-CSE'd. Used by pbvh_half_space_keeps_. */
template <typename T>
static inline T pbvh_plane_corner_val(T nx, T ny, T nz, T d, T x, T y, T z) {
    T t0 = (nx * x);
    T t1 = (ny * y);
    T t2 = (t0 + t1);
    T t3 = (nz * z);
    T t4 = (t2 + t3);
    T t5 = (t4 + d);
    return t5;
}

/* Source: Types.lean:28 Proved: unionBounds_contains_left/right */
template <typename T>
struct AabbT {
    T min_x, max_x;
    T min_y, max_y;
    T min_z, max_z;
};
using Aabb = AabbT<int64_t>;

/* Ring-polynomial provenance export: Π (1 - sign_bit(dᵢ)) over 6 axis diffs.
   Proved equivalent to short-circuit r128_le chains below via bitDecompose;
   see aabbOverlapsExpr in Codegen/CodeGen.lean + HilbertBroadphase.lean. */
template <typename T>
static inline T aabb_overlaps_ring(T a_min_x, T a_max_x, T a_min_y, T a_max_y, T a_min_z, T a_max_z, T b_min_x, T b_max_x, T b_min_y, T b_max_y, T b_min_z, T b_max_z, T s0, T s1, T s2, T s3, T s4, T s5) {
    T t0 = (T(-1) * s0);
    T t1 = (T(1) + t0);
    T t2 = (T(-1) * s1);
    T t3 = (T(1) + t2);
    T t4 = (t1 * t3);
    T t5 = (T(-1) * s2);
    T t6 = (T(1) + t5);
    T t7 = (t4 * t6);
    T t8 = (T(-1) * s3);
    T t9 = (T(1) + t8);
    T t10 = (t7 * t9);
    T t11 = (T(-1) * s4);
    T t12 = (T(1) + t11);
    T t13 = (t10 * t12);
    T t14 = (T(-1) * s5);
    T t15 = (T(1) + t14);
    T t16 = (t13 * t15);
    return t16;
}

/* ── Adapter-provided non-polynomial helpers (defined in predictive_bvh_adapter.h)
   Forward-declared here so generated tree code can call them at parse time.
   DO NOT define these in this file; definitions live in the adapter. */
extern R128 r128_sign_bit(R128 d);
extern R128 pbvh_r128_min(R128 a, R128 b);
extern R128 pbvh_r128_max(R128 a, R128 b);
extern Aabb aabb_union(const Aabb *a, const Aabb *o);
extern bool aabb_overlaps(const Aabb *a, const Aabb *o);
extern bool aabb_contains(const Aabb *a, const Aabb *inner);
extern bool aabb_contains_point(const Aabb *a, R128 x, R128 y, R128 z);
extern uint32_t clz30(uint32_t x);
extern R128 r128_half(R128 v);
extern uint32_t hilbert3d(uint32_t x, uint32_t y, uint32_t z);
extern void hilbert3d_inverse(uint32_t h, uint32_t *ox, uint32_t *oy, uint32_t *oz);
extern uint32_t hilbert_of_aabb(const Aabb *b, const Aabb *scene);
extern Aabb hilbert_cell_of(uint32_t code, uint32_t prefix_depth, const Aabb *scene);
extern uint32_t per_entity_delta_poly(R128 v, R128 a_half);

/* ── Lean-derived tick-rate-parametric formulas ──────────────────────────
   PBVH_SIM_TICK_HZ is the DEFAULT value (what the Lean proofs were
   evaluated at and what set_physics_ticks_per_second() should be
   initialized with at startup). Runtime consumers (Godot/C++) should
   read the engine's actual physics tick rate and pass it to the inline
   helpers below — never hardcode PBVH_SIM_TICK_HZ at use sites.

   Formulas mirror Core/Types.lean + Resources.lean exactly:
     hysteresisThreshold = simTickHz * 4
     latencyTicksFloor   = max(simTickHz / 10, 1)
     vMaxPhysical μm/tick = 10 * 1_000_000 / simTickHz
     aHalfMinForearm μm/tick² = ceil(1_400_000 / (2 * simTickHz²))
   ─────────────────────────────────────────────────────────────────────── */
#define PBVH_SIM_TICK_HZ 20u

static inline uint32_t pbvh_hysteresis_threshold(uint32_t hz) { return hz * 4u; }
static inline uint32_t pbvh_latency_ticks(uint32_t hz) {
    uint32_t t = hz / 10u; return t > 0u ? t : 1u;
}
static inline int64_t pbvh_v_max_physical_um_per_tick(uint32_t hz) {
    return (int64_t)(10 * 1000000) / (int64_t)(hz > 0u ? hz : 1u);
}
static inline uint64_t pbvh_accel_floor_um_per_tick2(uint32_t hz) {
    uint64_t h = (uint64_t)(hz > 0u ? hz : 1u);
    uint64_t d = 2ull * h * h;
    return (1400000ull + d - 1ull) / d;
}

/* Tick-rate-invariant constants (pure physical distances / velocities) */
#define PBVH_INTEREST_RADIUS_UM 5000000LL   /* μm */
#define PBVH_CURRENT_FUNNEL_PEAK_V_M_PER_S 60  /* m/s — C7 rip-current impulse cap; μm/tick = 60*1e6/hz */

/* Default-rate convenience values (evaluated at PBVH_SIM_TICK_HZ).
   Prefer the pbvh_* helpers above at runtime. */
#define PBVH_LATENCY_TICKS_DEFAULT 2u
#define PBVH_HYSTERESIS_THRESHOLD_DEFAULT 80u
#define PBVH_V_MAX_PHYSICAL_DEFAULT 500000LL  /* μm/tick */
#define PBVH_ACCEL_FLOOR_DEFAULT 1750ULL /* μm/tick² */
#define PBVH_CURRENT_FUNNEL_PEAK_V_UM_TICK_DEFAULT 3000000LL /* μm/tick */

/* ══════════════════════════════════════════════════════════════════════════
   EML ADVERSARIAL GAP BOUNDS (C1..C7, R128, e-graph optimized)
   Source: PredictiveBVH/Spatial/EMLAdversarialHeuristic.lean
   All physical constants (v_max, accel_floor, latency_ticks, sat_delta,
   v_funnel, chunk_origin_offset_um) are runtime parameters — pass the
   pbvh_* helpers from constantsC above, so the bounds track the engine's
   actual physics tick rate instead of the default baked into Types.lean.
   ══════════════════════════════════════════════════════════════════════════ */

template <typename T>
static inline T pbvh_eml_c1_velocity_injection_gap(T v_true, T v_max, T delta) {
    T t0 = (T(-1) * v_max);
    T t1 = (v_true + t0);
    T t2 = (t1 * delta);
    return t2;
}

template <typename T>
static inline T pbvh_eml_c2_acceleration_underreport_gap(T accel_floor, T delta) {
    T t0 = (delta * delta);
    T t1 = (accel_floor * t0);
    return t1;
}

template <typename T>
static inline T pbvh_eml_c3_portal_discontinuity_gap(T jump_um, T ghost_bound_um) {
    T t0 = (ghost_bound_um * T(-1));
    T t1 = (jump_um + t0);
    return t1;
}

template <typename T>
static inline T pbvh_eml_c4_lifecycle_gap_bound(T v, T latency_ticks) {
    T t0 = (v * latency_ticks);
    return t0;
}

template <typename T>
static inline T pbvh_eml_c5_satellite_rtt_gap(T v, T sat_delta, T local_delta) {
    T t0 = (T(-1) * local_delta);
    T t1 = (sat_delta + t0);
    T t2 = (v * t1);
    return t2;
}

template <typename T>
static inline T pbvh_eml_c6_coord_frame_offset_gap(T chunk_origin_offset_um) {

    return chunk_origin_offset_um;
}

template <typename T>
static inline T pbvh_eml_c7_segment_boundary_gap(T v_funnel, T v_max, T delta) {
    T t0 = (T(-1) * v_max);
    T t1 = (v_funnel + t0);
    T t2 = (t1 * delta);
    return t2;
}

/* ══════════════════════════════════════════════════════════════════════════
   AMOLEAN E-GRAPH OPTIMIZED KERNELS (R128)
   ══════════════════════════════════════════════════════════════════════════ */

template <typename T>
static inline T predictive_cost(T min_x, T max_x, T min_y, T max_y, T min_z, T max_z, T vx, T vy, T vz, T ax, T ay, T az, T ticks_ahead) {
    T t0 = (T(-1) * min_x);
    T t1 = (max_x + t0);
    T t2 = (vx * ticks_ahead);
    T t3 = (t1 + t2);
    T t4 = (ticks_ahead * ticks_ahead);
    T t5 = (ax * t4);
    T t6 = (t3 + t5);
    T t7 = (T(-1) * min_y);
    T t8 = (max_y + t7);
    T t9 = (vy * ticks_ahead);
    T t10 = (t8 + t9);
    T t11 = (ay * t4);
    T t12 = (t10 + t11);
    T t13 = (t6 * t12);
    T t14 = (T(-1) * min_z);
    T t15 = (max_z + t14);
    T t16 = (vz * ticks_ahead);
    T t17 = (t15 + t16);
    T t18 = (az * t4);
    T t19 = (t17 + t18);
    T t20 = (t12 * t19);
    T t21 = (t13 + t20);
    T t22 = (t6 * t19);
    T t23 = (t21 + t22);
    T t24 = (T(2) * t23);
    T t25 = (t24 + T(1));
    return t25;
}

template <typename T>
static inline T delta_cost_1(T v, T a_half) {
    T t0 = (v + a_half);
    return t0;
}

template <typename T>
static inline T delta_cost_2(T v, T a_half) {
    T t0 = (T(2) * v);
    T t1 = (T(4) * a_half);
    T t2 = (t0 + t1);
    return t2;
}

template <typename T>
static inline T delta_cost_4(T v, T a_half) {
    T t0 = (T(4) * v);
    T t1 = (T(16) * a_half);
    T t2 = (t0 + t1);
    return t2;
}

template <typename T>
static inline T delta_cost_8(T v, T a_half) {
    T t0 = (T(8) * v);
    T t1 = (T(64) * a_half);
    T t2 = (t0 + t1);
    return t2;
}

template <typename T>
static inline T delta_cost_16(T v, T a_half) {
    T t0 = (T(16) * v);
    T t1 = (T(256) * a_half);
    T t2 = (t0 + t1);
    return t2;
}

template <typename T>
static inline T delta_cost_24(T v, T a_half) {
    T t0 = (T(24) * v);
    T t1 = (T(576) * a_half);
    T t2 = (t0 + t1);
    return t2;
}

template <typename T>
static inline T delta_cost_32(T v, T a_half) {
    T t0 = (T(32) * v);
    T t1 = (T(1024) * a_half);
    T t2 = (t0 + t1);
    return t2;
}

template <typename T>
static inline T delta_cost_48(T v, T a_half) {
    T t0 = (T(48) * v);
    T t1 = (T(2304) * a_half);
    T t2 = (t0 + t1);
    return t2;
}

template <typename T>
static inline T delta_cost_64(T v, T a_half) {
    T t0 = (T(64) * v);
    T t1 = (T(4096) * a_half);
    T t2 = (t0 + t1);
    return t2;
}

template <typename T>
static inline T delta_cost_80(T v, T a_half) {
    T t0 = (T(80) * v);
    T t1 = (T(6400) * a_half);
    T t2 = (t0 + t1);
    return t2;
}

template <typename T>
static inline T delta_cost_100(T v, T a_half) {
    T t0 = (T(100) * v);
    T t1 = (T(10000) * a_half);
    T t2 = (t0 + t1);
    return t2;
}

template <typename T>
static inline T delta_cost_120(T v, T a_half) {
    T t0 = (T(120) * v);
    T t1 = (T(14400) * a_half);
    T t2 = (t0 + t1);
    return t2;
}

/* Quintic Hermite spline basis functions (C3 continuity).
   t = numer/denom in [0,1] where numer=ticks_since_build, denom=delta.
   Return values are integer numerators in μm units:
     h00, h01, h10, h11 : divide result by denom^5
     h20, h21            : divide result by 2*denom^5
   Source of truth: PredictiveBVH.QuinticHermite (C3 proofs in Lean). */
template <typename T>
static inline T bvh_h00(T numer, T denom) {
    T t0 = pow_int_T(denom, 5);
    T t1 = pow_int_T(numer, 3);
    T t2 = (T(10) * t1);
    T t3 = (denom * denom);
    T t4 = (t2 * t3);
    T t5 = (T(-1) * t4);
    T t6 = (t0 + t5);
    T t7 = pow_int_T(numer, 4);
    T t8 = (T(15) * t7);
    T t9 = (t8 * denom);
    T t10 = (t6 + t9);
    T t11 = pow_int_T(numer, 5);
    T t12 = (T(6) * t11);
    T t13 = (T(-1) * t12);
    T t14 = (t10 + t13);
    return t14;
}

template <typename T>
static inline T bvh_h01(T numer, T denom) {
    T t0 = pow_int_T(numer, 3);
    T t1 = (T(10) * t0);
    T t2 = (denom * denom);
    T t3 = (t1 * t2);
    T t4 = pow_int_T(numer, 4);
    T t5 = (T(15) * t4);
    T t6 = (t5 * denom);
    T t7 = (T(-1) * t6);
    T t8 = (t3 + t7);
    T t9 = pow_int_T(numer, 5);
    T t10 = (T(6) * t9);
    T t11 = (t8 + t10);
    return t11;
}

template <typename T>
static inline T bvh_h10(T numer, T denom) {
    T t0 = pow_int_T(denom, 4);
    T t1 = (numer * t0);
    T t2 = pow_int_T(numer, 3);
    T t3 = (T(6) * t2);
    T t4 = (denom * denom);
    T t5 = (t3 * t4);
    T t6 = (T(-1) * t5);
    T t7 = (t1 + t6);
    T t8 = pow_int_T(numer, 4);
    T t9 = (T(8) * t8);
    T t10 = (t9 * denom);
    T t11 = (t7 + t10);
    T t12 = pow_int_T(numer, 5);
    T t13 = (T(3) * t12);
    T t14 = (T(-1) * t13);
    T t15 = (t11 + t14);
    return t15;
}

template <typename T>
static inline T bvh_h11(T numer, T denom) {
    T t0 = pow_int_T(numer, 3);
    T t1 = (T(-4) * t0);
    T t2 = (denom * denom);
    T t3 = (t1 * t2);
    T t4 = pow_int_T(numer, 4);
    T t5 = (T(7) * t4);
    T t6 = (t5 * denom);
    T t7 = (t3 + t6);
    T t8 = pow_int_T(numer, 5);
    T t9 = (T(3) * t8);
    T t10 = (T(-1) * t9);
    T t11 = (t7 + t10);
    return t11;
}

template <typename T>
static inline T bvh_h20(T numer, T denom) {
    T t0 = (numer * numer);
    T t1 = pow_int_T(denom, 3);
    T t2 = (t0 * t1);
    T t3 = pow_int_T(numer, 3);
    T t4 = (T(3) * t3);
    T t5 = (denom * denom);
    T t6 = (t4 * t5);
    T t7 = (T(-1) * t6);
    T t8 = (t2 + t7);
    T t9 = pow_int_T(numer, 4);
    T t10 = (T(3) * t9);
    T t11 = (t10 * denom);
    T t12 = (t8 + t11);
    T t13 = pow_int_T(numer, 5);
    T t14 = (T(-1) * t13);
    T t15 = (t12 + t14);
    return t15;
}

template <typename T>
static inline T bvh_h21(T numer, T denom) {
    T t0 = pow_int_T(numer, 3);
    T t1 = (denom * denom);
    T t2 = (t0 * t1);
    T t3 = pow_int_T(numer, 4);
    T t4 = (T(2) * t3);
    T t5 = (t4 * denom);
    T t6 = (T(-1) * t5);
    T t7 = (t2 + t6);
    T t8 = pow_int_T(numer, 5);
    T t9 = (t7 + t8);
    return t9;
}

/* ══════════════════════════════════════════════════════════════════════════
   PBVH TREE (Hilbert-radix nested-set BVH; emitted from Spatial/Tree.lean)
   ══════════════════════════════════════════════════════════════════════════ */

typedef uint32_t pbvh_eclass_id_t;
typedef uint32_t pbvh_node_id_t;
typedef uint32_t pbvh_internal_id_t;

#define PBVH_NULL_NODE ((pbvh_node_id_t)0xFFFFFFFFu)

template <typename T>
struct pbvh_node {
	AabbT<T> bounds; /* 96 B (T × 6) */
	pbvh_eclass_id_t eclass;
	pbvh_node_id_t next_free; /* PBVH_NULL_NODE when live */
	uint32_t is_leaf;
	uint32_t hilbert; /* 30-bit Hilbert code; sort key */
};
using pbvh_node_t = pbvh_node<int64_t>;

/* Hilbert-radix internal node over sorted[]. Stored in pre-order DFS, so the
 * array itself is a nested set: the subtree rooted at internals[i] occupies
 * contiguous indices [i, skip). On each node, (offset, span) is the
 * corresponding range inside t->sorted[] — the leaf-side nested set. */
template <typename T>
struct pbvh_internal {
	AabbT<T> bounds; /* union of every leaf AABB in [offset, offset+span) */
	uint32_t offset; /* start index into t->sorted[] */
	uint32_t span; /* leaf count in this subtree */
	pbvh_internal_id_t skip; /* next DFS index after this subtree ends */
	pbvh_internal_id_t left; /* PBVH_NULL_NODE when this is a leaf-range node */
	pbvh_internal_id_t right; /* PBVH_NULL_NODE when this is a leaf-range node */
};
using pbvh_internal_t = pbvh_internal<int64_t>;

typedef struct pbvh_dirty_leaf {
	pbvh_node_id_t leaf_id;
	uint32_t old_hilbert;
} pbvh_dirty_leaf_t;

template <typename T>
struct pbvh_tree {
	pbvh_node<T> *nodes;
	uint32_t capacity;
	uint32_t count;
	pbvh_node_id_t root;
	pbvh_node_id_t free_head;
	/* Sorted-by-hilbert permutation of live leaf ids. Caller-owned, size capacity. */
	pbvh_node_id_t *sorted;
	uint32_t sorted_count;
	uint32_t last_visits; /* debug: # of leaves AABB-tested in the last query */
	/* Hilbert-radix internal tree over sorted[]. Mandatory for _n and _b
	 * queries. Caller-owned; size at least 2*capacity covers any split shape. */
	pbvh_internal<T> *internals;
	uint32_t internal_capacity;
	uint32_t internal_count;
	pbvh_internal_id_t internal_root;
	/* Optional bucket directory: bucket_dir[p] is the half-open range
	 * [lo, hi) of sorted[] indices whose Hilbert code has prefix p at
	 * bucket_bits. Size must be 1u << bucket_bits; two uint32 per entry
	 * laid out flat as [lo0, hi0, lo1, hi1, …]. Set bucket_bits=0 to skip. */
	uint32_t *bucket_dir;
	uint32_t bucket_bits;
	/* Optional incremental-refit sidecar (eclass-keyed, no parent pointers
	 * inside pbvh_internal_t). When all three are non-NULL, pbvh_tree_tick
	 * restricts its refit to the ancestor set of dirty leaves — O(K log N)
	 * touches instead of O(internal_count). leaf_to_internal[id] = the
	 * enclosing leaf-range internal id for leaf node id; parent_of_internal[i]
	 * = the immediately enclosing internal id (PBVH_NULL_NODE at root);
	 * touched_bits = internal_capacity-bit scratch, cleared each tick. */
	uint32_t *parent_of_internal; /* size internal_capacity, caller-owned */
	uint32_t *leaf_to_internal; /* size capacity, caller-owned, indexed by node id */
	uint64_t *touched_bits; /* size (internal_capacity + 63) / 64, caller-owned */
	/* Meta-bitmap over touched_bits: bit i in touched_meta_bits is set iff
	 * touched_bits[i] has any set bits. Lets the refit scan skip empty
	 * words in O(1) via __builtin_clzll instead of iterating the whole
	 * [min_word..max_word] range. Kills the N/64 term in the scan phase,
	 * leaving a strict O(K + n_marked) refit bound. */
	uint64_t *touched_meta_bits; /* size ((internal_capacity + 63)/64 + 63)/64, caller-owned */
};
using pbvh_tree_t = pbvh_tree<int64_t>;

/* ============================================================================
 * BUCKET AUTO-TUNE (Phase 2e)
 *
 * Target max entities per bucket. Controls the constant-time upper bound on
 * pbvh_tree_aabb_query_b's per-bucket scan: a bucket cannot exceed
 * ceil(N / (1 << bucket_bits)) entities, so bucket_bits = ceil(log2(N/K))
 * gives at most K entities per bucket under uniform Hilbert distribution.
 * Empirical max/mean on uniform random inputs is ~1.06-1.30x (sub-Poisson),
 * so a K_TARGET of 32 yields worst-case ~40-entity scans at any N.
 * ========================================================================= */
#ifndef PBVH_BUCKET_K_TARGET
#define PBVH_BUCKET_K_TARGET 32u
#endif


#endif /* PREDICTIVE_BVH_H */
