// Generated by lake exe bvh-codegen (AmoLean E-graph pipeline).
//
// MIT License
//
// Copyright (c) 2026-present K. S. Ernest (iFire) Lee
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.
//
// All arithmetic: Expr Int → optimizeBasic → generateRustFunction.
// Spatial primitives: direct Lean translations with proof references.
// Source: PredictiveBVH/{Formula,State,Build,LowerBound,HilbertBroadphase}.lean
// DO NOT EDIT — re-run lake exe bvh-codegen to regenerate.
#[allow(clippy::all, unused_parens, non_snake_case, dead_code)]

use fixed::types::I64F64;

// ══════════════════════════════════════════════════════════════════════════
// PROVED SPATIAL PRIMITIVES
// Polynomial: AmoLean Expr Int → optimizeBasic (E-graph) → Rust
// Non-polynomial (bit/cmp): proved Lean definitions, not E-graph expressible
// ══════════════════════════════════════════════════════════════════════════

/// Ghost expansion v·δ + a_half·δ². Proved: expansion_covers_k_ticks
#[inline(always)]
pub fn ghost_bound(v: I64F64, a_half: I64F64, ticks_ahead: I64F64) -> I64F64 {
    let t0: I64F64 = (v * ticks_ahead);
    let t1: I64F64 = (a_half * ticks_ahead);
    let t2: I64F64 = (t1 * ticks_ahead);
    let t3: I64F64 = (t0 + t2);
    t3
}

/// Surface area 2(wh+hd+wd). Proved: surfaceArea_nonneg
#[inline(always)]
pub fn surface_area(w: I64F64, h: I64F64, d: I64F64) -> I64F64 {
    let t0: I64F64 = (w * h);
    let t1: I64F64 = (h * d);
    let t2: I64F64 = (t0 + t1);
    let t3: I64F64 = (w * d);
    let t4: I64F64 = (t2 + t3);
    let t5: I64F64 = (I64F64::from_num(2i64) * t4);
    t5
}

/// Ghost AABB min bound per axis. Proved: expansion_covers_k_ticks
#[inline(always)]
pub fn ghost_aabb_min(center: I64F64, ext: I64F64, v: I64F64, a_half: I64F64, tau: I64F64) -> I64F64 {
    let t0: I64F64 = ((-I64F64::ONE) * ext);
    let t1: I64F64 = (center + t0);
    let t2: I64F64 = (v * tau);
    let t3: I64F64 = (a_half * tau);
    let t4: I64F64 = (t3 * tau);
    let t5: I64F64 = (t2 + t4);
    let t6: I64F64 = ((-I64F64::ONE) * t5);
    let t7: I64F64 = (t1 + t6);
    t7
}

/// Ghost AABB max bound per axis. Proved: expansion_covers_k_ticks
#[inline(always)]
pub fn ghost_aabb_max(center: I64F64, ext: I64F64, v: I64F64, a_half: I64F64, tau: I64F64) -> I64F64 {
    let t0: I64F64 = (center + ext);
    let t1: I64F64 = (v * tau);
    let t2: I64F64 = (a_half * tau);
    let t3: I64F64 = (t2 * tau);
    let t4: I64F64 = (t1 + t3);
    let t5: I64F64 = (t0 + t4);
    t5
}

/// Batch SAH: mapScalarExpr(predictiveCostFormula, entityMatrix)
/// Generated via MatExpr → SigmaExpr → ExpandedSigma → Rust
/// Each row: [minX,maxX,minY,maxY,minZ,maxZ,vx,vy,vz,ax,ay,az,ticksAhead]
// Generated by AMO-Lean Sigma-SPL Rust CodeGen (R128 fixed-point backend)


pub fn batch_sah(input: &[I64F64], output: &mut [I64F64]) {
    output[0 + 0] = input[0 + 0];
    output[0 + 1] = input[0 + 1];
    output[0 + 2] = input[0 + 2];
    output[0 + 3] = input[0 + 3];
    output[0 + 4] = input[0 + 4];
    output[0 + 5] = input[0 + 5];
    output[0 + 6] = input[0 + 6];
    output[0 + 7] = input[0 + 7];
    for i0 in 0..8 {
        let t0: I64F64 = ((-I64F64::from_num(1i64)) * input[8 * i0 + 0]);
        let t1: I64F64 = (input[8 * i0 + 1] + t0);
        let t2: I64F64 = (input[8 * i0 + 6] * input[8 * i0 + 12]);
        let t3: I64F64 = (t1 + t2);
        let t4: I64F64 = (input[8 * i0 + 12] * input[8 * i0 + 12]);
        let t5: I64F64 = (input[8 * i0 + 9] * t4);
        let t6: I64F64 = (t3 + t5);
        let t7: I64F64 = ((-I64F64::from_num(1i64)) * input[8 * i0 + 2]);
        let t8: I64F64 = (input[8 * i0 + 3] + t7);
        let t9: I64F64 = (input[8 * i0 + 7] * input[8 * i0 + 12]);
        let t10: I64F64 = (t8 + t9);
        let t11: I64F64 = (input[8 * i0 + 10] * t4);
        let t12: I64F64 = (t10 + t11);
        let t13: I64F64 = (t6 * t12);
        let t14: I64F64 = ((-I64F64::from_num(1i64)) * input[8 * i0 + 4]);
        let t15: I64F64 = (input[8 * i0 + 5] + t14);
        let t16: I64F64 = (input[8 * i0 + 8] * input[8 * i0 + 12]);
        let t17: I64F64 = (t15 + t16);
        let t18: I64F64 = (input[8 * i0 + 11] * t4);
        let t19: I64F64 = (t17 + t18);
        let t20: I64F64 = (t12 * t19);
        let t21: I64F64 = (t13 + t20);
        let t22: I64F64 = (t6 * t19);
        let t23: I64F64 = (t21 + t22);
        let t24: I64F64 = (I64F64::from_num(2i64) * t23);
        let t25: I64F64 = (t24 + I64F64::ONE);
        output[i0 + 0] = t25;
    }
}

/// Source: Types.lean:28 Proved: unionBounds_contains_left/right, aabbOverlapsDec_false_implies_disjoint
#[derive(Clone, Copy, Debug, Default)]
pub struct Aabb {
    pub min_x: i64, pub max_x: i64,
    pub min_y: i64, pub max_y: i64,
    pub min_z: i64, pub max_z: i64,
}

impl Aabb {
    pub fn union(&self, o: &Aabb) -> Aabb {
        Aabb { min_x: self.min_x.min(o.min_x), max_x: self.max_x.max(o.max_x),
               min_y: self.min_y.min(o.min_y), max_y: self.max_y.max(o.max_y),
               min_z: self.min_z.min(o.min_z), max_z: self.max_z.max(o.max_z) }
    }
    pub fn overlaps(&self, o: &Aabb) -> bool {
        self.min_x <= o.max_x && o.min_x <= self.max_x
            && self.min_y <= o.max_y && o.min_y <= self.max_y
            && self.min_z <= o.max_z && o.min_z <= self.max_z
    }
    pub fn contains(&self, inner: &Aabb) -> bool {
        self.min_x <= inner.min_x && inner.max_x <= self.max_x
            && self.min_y <= inner.min_y && inner.max_y <= self.max_y
            && self.min_z <= inner.min_z && inner.max_z <= self.max_z
    }
    pub fn contains_point(&self, x: i64, y: i64, z: i64) -> bool {
        self.min_x <= x && x <= self.max_x && self.min_y <= y && y <= self.max_y
            && self.min_z <= z && z <= self.max_z
    }
}

/// Source: Build.lean:193 (clz30)
pub fn clz30(x: u32) -> u32 { if x == 0 { 30 } else { 29 - (31 - x.leading_zeros()) } }

/// Source: Build.lean (hilbert3D) — Skilling (2004) 3D Hilbert curve.
pub fn hilbert3d(mut x: u32, mut y: u32, mut z: u32) -> u32 {
    let order: u32 = 10;
    let mask: u32 = (1 << order) - 1;
    x &= mask; y &= mask; z &= mask;
    for i in 0..order-1 {
        let q = 1u32 << (order - 1 - i);
        let p = q - 1;
        if z & q != 0 { x ^= p; } else { let t = (x ^ z) & p; x ^= t; z ^= t; }
        if y & q != 0 { x ^= p; } else { let t = (x ^ y) & p; x ^= t; y ^= t; }
    }
    y ^= x; z ^= y;
    let mut t: u32 = 0;
    for i in 0..order-1 {
        let q = 1u32 << (order - 1 - i);
        if z & q != 0 { t ^= q - 1; }
    }
    x ^= t; y ^= t; z ^= t;
    x &= mask; y &= mask; z &= mask;
    let mut h: u32 = 0;
    for b in (0..order).rev() {
        h = (h << 1) | ((z >> b) & 1);
        h = (h << 1) | ((y >> b) & 1);
        h = (h << 1) | ((x >> b) & 1);
    }
    h
}

/// Source: Build.lean (leafHilbert)
pub fn hilbert_of_aabb(b: &Aabb, scene: &Aabb) -> u32 {
    let sw = (scene.max_x-scene.min_x).max(1);
    let sh = (scene.max_y-scene.min_y).max(1);
    let sd = (scene.max_z-scene.min_z).max(1);
    let nx = (((b.min_x+b.max_x)/2 - scene.min_x)*1024/sw) as u32;
    let ny = (((b.min_y+b.max_y)/2 - scene.min_y)*1024/sh) as u32;
    let nz = (((b.min_z+b.max_z)/2 - scene.min_z)*1024/sd) as u32;
    hilbert3d(nx.min(1023), ny.min(1023), nz.min(1023))
}

/// Branchless min via Z↔GF(2) bridge. sign = sign_bit(b-a) from witness.
#[inline(always)]
pub fn ring_min(a: I64F64, b: I64F64, sign: I64F64) -> I64F64 {
    let t0: I64F64 = ((-I64F64::ONE) * a);
    let t1: I64F64 = (b + t0);
    let t2: I64F64 = (sign * t1);
    let t3: I64F64 = (a + t2);
    t3
}

/// Branchless max via Z↔GF(2) bridge. sign = sign_bit(b-a) from witness.
#[inline(always)]
pub fn ring_max(a: I64F64, b: I64F64, sign: I64F64) -> I64F64 {
    let t0: I64F64 = ((-I64F64::ONE) * a);
    let t1: I64F64 = (b + t0);
    let t2: I64F64 = (sign * t1);
    let t3: I64F64 = ((-I64F64::ONE) * t2);
    let t4: I64F64 = (b + t3);
    t4
}

/// Aabb union via branchless min/max (Z↔GF(2) bridge).
#[inline]
pub fn aabb_union_bridge(a: &Aabb, b: &Aabb) -> Aabb {
    let s = |d: i64| I64F64::from_num((d >> 63) & 1);
    Aabb {
        min_x: ring_min(I64F64::from_num(a.min_x), I64F64::from_num(b.min_x), s(b.min_x - a.min_x)).to_num(),
        max_x: ring_max(I64F64::from_num(a.max_x), I64F64::from_num(b.max_x), s(b.max_x - a.max_x)).to_num(),
        min_y: ring_min(I64F64::from_num(a.min_y), I64F64::from_num(b.min_y), s(b.min_y - a.min_y)).to_num(),
        max_y: ring_max(I64F64::from_num(a.max_y), I64F64::from_num(b.max_y), s(b.max_y - a.max_y)).to_num(),
        min_z: ring_min(I64F64::from_num(a.min_z), I64F64::from_num(b.min_z), s(b.min_z - a.min_z)).to_num(),
        max_z: ring_max(I64F64::from_num(a.max_z), I64F64::from_num(b.max_z), s(b.max_z - a.max_z)).to_num(),
    }
}

/// Aabb contains via Z↔GF(2) bridge: 6 sign-bit checks.
#[inline]
pub fn aabb_contains_bridge(outer: &Aabb, inner: &Aabb) -> bool {
    let s = |d: i64| -> I64F64 { I64F64::from_num((d >> 63) & 1) };
    let r = I64F64::from_num;
    aabb_overlaps_ring(
        r(outer.min_x), r(inner.min_x), r(outer.min_y), r(inner.min_y), r(outer.min_z), r(inner.min_z),
        r(inner.min_x), r(outer.max_x), r(inner.min_y), r(outer.max_y), r(inner.min_z), r(outer.max_z),
        s(inner.min_x - outer.min_x), s(outer.max_x - inner.max_x),
        s(inner.min_y - outer.min_y), s(outer.max_y - inner.max_y),
        s(inner.min_z - outer.min_z), s(outer.max_z - inner.max_z)
    ) == I64F64::ONE
}

/// AABB overlap test via Z↔GF(2) bridge: pure ring polynomial.
/// sign bits s0..s5 are witness variables from bitDecompose of the 6 differences.
/// Returns I64F64::ONE if overlaps, I64F64::ZERO if not.
/// Proved: aabbOverlapsDec_false_implies_disjoint (HilbertBroadphase.lean)
#[inline(always)]
pub fn aabb_overlaps_ring(a_min_x: I64F64, a_max_x: I64F64, a_min_y: I64F64, a_max_y: I64F64, a_min_z: I64F64, a_max_z: I64F64, b_min_x: I64F64, b_max_x: I64F64, b_min_y: I64F64, b_max_y: I64F64, b_min_z: I64F64, b_max_z: I64F64, s0: I64F64, s1: I64F64, s2: I64F64, s3: I64F64, s4: I64F64, s5: I64F64) -> I64F64 {
    let t0: I64F64 = ((-I64F64::ONE) * s0);
    let t1: I64F64 = (I64F64::ONE + t0);
    let t2: I64F64 = ((-I64F64::ONE) * s1);
    let t3: I64F64 = (I64F64::ONE + t2);
    let t4: I64F64 = (t1 * t3);
    let t5: I64F64 = ((-I64F64::ONE) * s2);
    let t6: I64F64 = (I64F64::ONE + t5);
    let t7: I64F64 = (t4 * t6);
    let t8: I64F64 = ((-I64F64::ONE) * s3);
    let t9: I64F64 = (I64F64::ONE + t8);
    let t10: I64F64 = (t7 * t9);
    let t11: I64F64 = ((-I64F64::ONE) * s4);
    let t12: I64F64 = (I64F64::ONE + t11);
    let t13: I64F64 = (t10 * t12);
    let t14: I64F64 = ((-I64F64::ONE) * s5);
    let t15: I64F64 = (I64F64::ONE + t14);
    let t16: I64F64 = (t13 * t15);
    t16
}

/// AABB overlap via Z↔GF(2) bridge: witness sign-bit extraction + ring verification.
#[inline]
pub fn aabb_overlaps_bridge(a: &Aabb, b: &Aabb) -> bool {
    // 6 differences (Z arithmetic)
    let d0 = b.max_x - a.min_x;
    let d1 = a.max_x - b.min_x;
    let d2 = b.max_y - a.min_y;
    let d3 = a.max_y - b.min_y;
    let d4 = b.max_z - a.min_z;
    let d5 = a.max_z - b.min_z;
    // Witness: extract sign bits (bit 63 of each i64 difference)
    let s0 = I64F64::from_num((d0 >> 63) & 1);
    let s1 = I64F64::from_num((d1 >> 63) & 1);
    let s2 = I64F64::from_num((d2 >> 63) & 1);
    let s3 = I64F64::from_num((d3 >> 63) & 1);
    let s4 = I64F64::from_num((d4 >> 63) & 1);
    let s5 = I64F64::from_num((d5 >> 63) & 1);
    // Ring: product of (1 - sᵢ) = 1 iff all non-negative
    aabb_overlaps_ring(
        I64F64::from_num(a.min_x), I64F64::from_num(a.max_x),
        I64F64::from_num(a.min_y), I64F64::from_num(a.max_y),
        I64F64::from_num(a.min_z), I64F64::from_num(a.max_z),
        I64F64::from_num(b.min_x), I64F64::from_num(b.max_x),
        I64F64::from_num(b.min_y), I64F64::from_num(b.max_y),
        I64F64::from_num(b.min_z), I64F64::from_num(b.max_z),
        s0, s1, s2, s3, s4, s5
    ) == I64F64::ONE
}

/// clz30 bridge: delegates to the 1-line imperative clz30.
/// Ring polynomial (clz30_ring) removed — 1,402 lines of dead code.
#[inline]
pub fn clz30_bridge(x: u32) -> u32 { clz30(x) }

/// Hilbert3D bridge: delegates to imperative hilbert3d.
#[inline]
pub fn hilbert3d_bridge(x: u32, y: u32, z: u32) -> u32 {
    let h = hilbert3d(x, y, z);
    let (rx, ry, rz) = hilbert3d_inverse_bridge(h);
    debug_assert!(rx == x && ry == y && rz == z, "hilbert3d witness check failed");
    h
}

/// Hilbert-of-AABB bridge.
#[inline]
pub fn hilbert_of_aabb_bridge(b: &Aabb, scene: &Aabb) -> u32 {
    let sw = (scene.max_x - scene.min_x).max(1);
    let sh = (scene.max_y - scene.min_y).max(1);
    let sd = (scene.max_z - scene.min_z).max(1);
    let nx = (((b.min_x+b.max_x)/2 - scene.min_x)*1024/sw) as u32;
    let ny = (((b.min_y+b.max_y)/2 - scene.min_y)*1024/sh) as u32;
    let nz = (((b.min_z+b.max_z)/2 - scene.min_z)*1024/sd) as u32;
    hilbert3d_bridge(nx.min(1023), ny.min(1023), nz.min(1023))
}

/// Hilbert3D inverse: 30-bit Hilbert code → (x, y, z) 10-bit coordinates.
/// Skilling transposeToAxes. Verified by roundtrip against hilbert3d_ring.
#[inline]
pub fn hilbert3d_inverse_bridge(h: u32) -> (u32, u32, u32) {
    let order: u32 = 10;
    let mask: u32 = (1 << order) - 1;
    // Deinterleave: extract transpose coordinates
    let (mut x, mut y, mut z) = (0u32, 0u32, 0u32);
    for b in 0..order {
        let s = 3 * b;
        x |= ((h >> s) & 1) << b;
        y |= ((h >> (s + 1)) & 1) << b;
        z |= ((h >> (s + 2)) & 1) << b;
    }
    // Undo fixup: progressive decode
    let mut t: u32 = 0;
    for i in 0..(order - 1) {
        let q = 1u32 << (order - 1 - i);
        if (z ^ t) & q != 0 { t ^= q - 1; }
    }
    x ^= t; y ^= t; z ^= t;
    // Undo Gray: z ^= y, then y ^= x
    z ^= y; y ^= x;
    // Undo main loop: Q from 2 to MSB, y then z exchanges
    let mut q: u32 = 2;
    while q < (1u32 << order) {
        let p = q - 1;
        if y & q != 0 { x ^= p; } else { let t = (x ^ y) & p; x ^= t; y ^= t; }
        if z & q != 0 { x ^= p; } else { let t = (x ^ z) & p; x ^= t; z ^= t; }
        q <<= 1;
    }
    let (x, y, z) = (x & mask, y & mask, z & mask);
    debug_assert_eq!(hilbert3d(x, y, z), h, "hilbert3d_inverse witness check failed");
    (x, y, z)
}

/// Hilbert-cell-of: recover AABB from Hilbert code range + scene bounds.
#[inline]
pub fn hilbert_cell_of_bridge(code: u32, prefix_depth: u32, scene: &Aabb) -> Aabb {
    let (x, y, z) = hilbert3d_inverse_bridge(code);
    let sw = (scene.max_x - scene.min_x).max(1);
    let sh = (scene.max_y - scene.min_y).max(1);
    let sd = (scene.max_z - scene.min_z).max(1);
    let shift = 10u32.saturating_sub(prefix_depth);
    let cell = 1i64 << shift;
    let x0 = (x >> shift) << shift;
    let y0 = (y >> shift) << shift;
    let z0 = (z >> shift) << shift;
    Aabb {
        min_x: scene.min_x + (x0 as i64) * sw / 1024,
        max_x: scene.min_x + ((x0 as i64) + cell) * sw / 1024,
        min_y: scene.min_y + (y0 as i64) * sh / 1024,
        max_y: scene.min_y + ((y0 as i64) + cell) * sh / 1024,
        min_z: scene.min_z + (z0 as i64) * sd / 1024,
        max_z: scene.min_z + ((z0 as i64) + cell) * sd / 1024,
    }
}

// Lean-derived tick-rate-parametric formulas. PBVH_SIM_TICK_HZ is the default
// value the Lean proofs were evaluated at; runtime consumers should pass the
// engine's actual physics tick rate to the pbvh_* helpers below.
pub const PBVH_SIM_TICK_HZ: u32 = 20;

#[inline] pub const fn pbvh_hysteresis_threshold(hz: u32) -> u32 { hz * 4 }
#[inline] pub const fn pbvh_latency_ticks(hz: u32) -> u32 {
    let t = hz / 10; if t > 0 { t } else { 1 }
}
#[inline] pub const fn pbvh_v_max_physical_um_per_tick(hz: u32) -> i64 {
    (10i64 * 1_000_000i64) / (if hz > 0 { hz } else { 1 } as i64)
}
#[inline] pub const fn pbvh_accel_floor_um_per_tick2(hz: u32) -> u64 {
    let h = (if hz > 0 { hz } else { 1 }) as u64;
    let d = 2u64 * h * h;
    (1_400_000u64 + d - 1) / d
}

// Tick-rate-invariant physical constants
pub const PBVH_INTEREST_RADIUS_UM: i64 = 5000000; // μm
pub const PBVH_CURRENT_FUNNEL_PEAK_V_M_PER_S: u32 = 60; // m/s (μm/tick = 60*1e6/hz)

// Default-rate convenience values (evaluated at PBVH_SIM_TICK_HZ)
pub const PBVH_LATENCY_TICKS_DEFAULT: u32 = 2;
pub const PBVH_HYSTERESIS_THRESHOLD_DEFAULT: u32 = 80;
pub const PBVH_V_MAX_PHYSICAL_DEFAULT: i64 = 500000; // μm/tick
pub const PBVH_ACCEL_FLOOR_DEFAULT: u64 = 1750; // μm/tick²
pub const PBVH_CURRENT_FUNNEL_PEAK_V_UM_TICK_DEFAULT: i64 = 3000000; // μm/tick

// ══════════════════════════════════════════════════════════════════════════
// AMOLEAN E-GRAPH OPTIMIZED KERNELS
// ══════════════════════════════════════════════════════════════════════════

fn pow_int(base: I64F64, exp: I64F64) -> I64F64 {
    let mut r = I64F64::ONE; let mut b = base; let mut e = exp.to_num::<i64>();
    while e > 0 { if e & 1 == 1 { r = r.wrapping_mul(b); } b = b.wrapping_mul(b); e >>= 1; } r
}

#[inline(always)]
pub fn predictive_cost(min_x: I64F64, max_x: I64F64, min_y: I64F64, max_y: I64F64, min_z: I64F64, max_z: I64F64, vx: I64F64, vy: I64F64, vz: I64F64, ax: I64F64, ay: I64F64, az: I64F64, ticks_ahead: I64F64) -> I64F64 {
    let t0: I64F64 = ((-I64F64::ONE) * min_x);
    let t1: I64F64 = (max_x + t0);
    let t2: I64F64 = (vx * ticks_ahead);
    let t3: I64F64 = (t1 + t2);
    let t4: I64F64 = (ticks_ahead * ticks_ahead);
    let t5: I64F64 = (ax * t4);
    let t6: I64F64 = (t3 + t5);
    let t7: I64F64 = ((-I64F64::ONE) * min_y);
    let t8: I64F64 = (max_y + t7);
    let t9: I64F64 = (vy * ticks_ahead);
    let t10: I64F64 = (t8 + t9);
    let t11: I64F64 = (ay * t4);
    let t12: I64F64 = (t10 + t11);
    let t13: I64F64 = (t6 * t12);
    let t14: I64F64 = ((-I64F64::ONE) * min_z);
    let t15: I64F64 = (max_z + t14);
    let t16: I64F64 = (vz * ticks_ahead);
    let t17: I64F64 = (t15 + t16);
    let t18: I64F64 = (az * t4);
    let t19: I64F64 = (t17 + t18);
    let t20: I64F64 = (t12 * t19);
    let t21: I64F64 = (t13 + t20);
    let t22: I64F64 = (t6 * t19);
    let t23: I64F64 = (t21 + t22);
    let t24: I64F64 = (I64F64::from_num(2i64) * t23);
    let t25: I64F64 = (t24 + I64F64::ONE);
    t25
}

#[inline(always)]
pub fn delta_cost_1(v: I64F64, a_half: I64F64) -> I64F64 {
    let t0: I64F64 = (v + a_half);
    t0
}

#[inline(always)]
pub fn delta_cost_2(v: I64F64, a_half: I64F64) -> I64F64 {
    let t0: I64F64 = (I64F64::from_num(2i64) * v);
    let t1: I64F64 = (I64F64::from_num(4i64) * a_half);
    let t2: I64F64 = (t0 + t1);
    t2
}

#[inline(always)]
pub fn delta_cost_4(v: I64F64, a_half: I64F64) -> I64F64 {
    let t0: I64F64 = (I64F64::from_num(4i64) * v);
    let t1: I64F64 = (I64F64::from_num(16i64) * a_half);
    let t2: I64F64 = (t0 + t1);
    t2
}

#[inline(always)]
pub fn delta_cost_8(v: I64F64, a_half: I64F64) -> I64F64 {
    let t0: I64F64 = (I64F64::from_num(8i64) * v);
    let t1: I64F64 = (I64F64::from_num(64i64) * a_half);
    let t2: I64F64 = (t0 + t1);
    t2
}

#[inline(always)]
pub fn delta_cost_16(v: I64F64, a_half: I64F64) -> I64F64 {
    let t0: I64F64 = (I64F64::from_num(16i64) * v);
    let t1: I64F64 = (I64F64::from_num(256i64) * a_half);
    let t2: I64F64 = (t0 + t1);
    t2
}

#[inline(always)]
pub fn delta_cost_24(v: I64F64, a_half: I64F64) -> I64F64 {
    let t0: I64F64 = (I64F64::from_num(24i64) * v);
    let t1: I64F64 = (I64F64::from_num(576i64) * a_half);
    let t2: I64F64 = (t0 + t1);
    t2
}

#[inline(always)]
pub fn delta_cost_32(v: I64F64, a_half: I64F64) -> I64F64 {
    let t0: I64F64 = (I64F64::from_num(32i64) * v);
    let t1: I64F64 = (I64F64::from_num(1024i64) * a_half);
    let t2: I64F64 = (t0 + t1);
    t2
}

#[inline(always)]
pub fn delta_cost_48(v: I64F64, a_half: I64F64) -> I64F64 {
    let t0: I64F64 = (I64F64::from_num(48i64) * v);
    let t1: I64F64 = (I64F64::from_num(2304i64) * a_half);
    let t2: I64F64 = (t0 + t1);
    t2
}

#[inline(always)]
pub fn delta_cost_64(v: I64F64, a_half: I64F64) -> I64F64 {
    let t0: I64F64 = (I64F64::from_num(64i64) * v);
    let t1: I64F64 = (I64F64::from_num(4096i64) * a_half);
    let t2: I64F64 = (t0 + t1);
    t2
}

#[inline(always)]
pub fn delta_cost_80(v: I64F64, a_half: I64F64) -> I64F64 {
    let t0: I64F64 = (I64F64::from_num(80i64) * v);
    let t1: I64F64 = (I64F64::from_num(6400i64) * a_half);
    let t2: I64F64 = (t0 + t1);
    t2
}

#[inline(always)]
pub fn delta_cost_100(v: I64F64, a_half: I64F64) -> I64F64 {
    let t0: I64F64 = (I64F64::from_num(100i64) * v);
    let t1: I64F64 = (I64F64::from_num(10000i64) * a_half);
    let t2: I64F64 = (t0 + t1);
    t2
}

#[inline(always)]
pub fn delta_cost_120(v: I64F64, a_half: I64F64) -> I64F64 {
    let t0: I64F64 = (I64F64::from_num(120i64) * v);
    let t1: I64F64 = (I64F64::from_num(14400i64) * a_half);
    let t2: I64F64 = (t0 + t1);
    t2
}

/// Per-entity δ: largest candidate where v·δ + ah·δ² ≤ R.
/// Polynomial cost evaluation via E-graph; selection is non-ring postprocessing.
/// Source of truth: perEntityDelta (Sim.lean:407)
#[inline]
pub fn per_entity_delta_poly(v: I64F64, a_half: I64F64) -> u32 {
    if delta_cost_120(v, a_half) <= I64F64::from_num(5000000i64) { return 120; }
    if delta_cost_100(v, a_half) <= I64F64::from_num(5000000i64) { return 100; }
    if delta_cost_80(v, a_half) <= I64F64::from_num(5000000i64) { return 80; }
    if delta_cost_64(v, a_half) <= I64F64::from_num(5000000i64) { return 64; }
    if delta_cost_48(v, a_half) <= I64F64::from_num(5000000i64) { return 48; }
    if delta_cost_32(v, a_half) <= I64F64::from_num(5000000i64) { return 32; }
    if delta_cost_24(v, a_half) <= I64F64::from_num(5000000i64) { return 24; }
    if delta_cost_16(v, a_half) <= I64F64::from_num(5000000i64) { return 16; }
    if delta_cost_8(v, a_half) <= I64F64::from_num(5000000i64) { return 8; }
    if delta_cost_4(v, a_half) <= I64F64::from_num(5000000i64) { return 4; }
    if delta_cost_2(v, a_half) <= I64F64::from_num(5000000i64) { return 2; }
    if delta_cost_1(v, a_half) <= I64F64::from_num(5000000i64) { return 1; }
    1
}


/// Quintic Hermite spline basis functions (C³ continuity).
/// t = numer/denom ∈ [0,1] where numer=ticks_since_build, denom=delta.
/// Return values are integer numerators in μm units:
///   h00, h01, h10, h11 : divide result by denom^5
///   h20, h21            : divide result by 2·denom^5
/// Interpolated position (μm):
///   pos = (h00*p0 + h01*p1 + h10*v0*T + h11*v1*T + h20*a0*T² + h21*a1*T²) / denom^5
/// where T = delta (ticks), p in μm, v in μm/tick, a in μm/tick².
/// Source of truth: PredictiveBVH.QuinticHermite (C³ proofs in Lean).
/// h00(t) numerator (÷ denom^5): position weight at t=0
#[inline(always)]
pub fn bvh_h00(numer: I64F64, denom: I64F64) -> I64F64 {
    let t0: I64F64 = pow_int(denom, I64F64::from_num(5i64));
    let t1: I64F64 = pow_int(numer, I64F64::from_num(3i64));
    let t2: I64F64 = (I64F64::from_num(10i64) * t1);
    let t3: I64F64 = (denom * denom);
    let t4: I64F64 = (t2 * t3);
    let t5: I64F64 = ((-I64F64::ONE) * t4);
    let t6: I64F64 = (t0 + t5);
    let t7: I64F64 = pow_int(numer, I64F64::from_num(4i64));
    let t8: I64F64 = (I64F64::from_num(15i64) * t7);
    let t9: I64F64 = (t8 * denom);
    let t10: I64F64 = (t6 + t9);
    let t11: I64F64 = pow_int(numer, I64F64::from_num(5i64));
    let t12: I64F64 = (I64F64::from_num(6i64) * t11);
    let t13: I64F64 = ((-I64F64::ONE) * t12);
    let t14: I64F64 = (t10 + t13);
    t14
}

/// h01(t) numerator (÷ denom^5): position weight at t=1
#[inline(always)]
pub fn bvh_h01(numer: I64F64, denom: I64F64) -> I64F64 {
    let t0: I64F64 = pow_int(numer, I64F64::from_num(3i64));
    let t1: I64F64 = (I64F64::from_num(10i64) * t0);
    let t2: I64F64 = (denom * denom);
    let t3: I64F64 = (t1 * t2);
    let t4: I64F64 = pow_int(numer, I64F64::from_num(4i64));
    let t5: I64F64 = (I64F64::from_num(15i64) * t4);
    let t6: I64F64 = (t5 * denom);
    let t7: I64F64 = ((-I64F64::ONE) * t6);
    let t8: I64F64 = (t3 + t7);
    let t9: I64F64 = pow_int(numer, I64F64::from_num(5i64));
    let t10: I64F64 = (I64F64::from_num(6i64) * t9);
    let t11: I64F64 = (t8 + t10);
    t11
}

/// h10(t) numerator (÷ denom^5): velocity×T weight at t=0
#[inline(always)]
pub fn bvh_h10(numer: I64F64, denom: I64F64) -> I64F64 {
    let t0: I64F64 = pow_int(denom, I64F64::from_num(4i64));
    let t1: I64F64 = (numer * t0);
    let t2: I64F64 = pow_int(numer, I64F64::from_num(3i64));
    let t3: I64F64 = (I64F64::from_num(6i64) * t2);
    let t4: I64F64 = (denom * denom);
    let t5: I64F64 = (t3 * t4);
    let t6: I64F64 = ((-I64F64::ONE) * t5);
    let t7: I64F64 = (t1 + t6);
    let t8: I64F64 = pow_int(numer, I64F64::from_num(4i64));
    let t9: I64F64 = (I64F64::from_num(8i64) * t8);
    let t10: I64F64 = (t9 * denom);
    let t11: I64F64 = (t7 + t10);
    let t12: I64F64 = pow_int(numer, I64F64::from_num(5i64));
    let t13: I64F64 = (I64F64::from_num(3i64) * t12);
    let t14: I64F64 = ((-I64F64::ONE) * t13);
    let t15: I64F64 = (t11 + t14);
    t15
}

/// h11(t) numerator (÷ denom^5): velocity×T weight at t=1
#[inline(always)]
pub fn bvh_h11(numer: I64F64, denom: I64F64) -> I64F64 {
    let t0: I64F64 = pow_int(numer, I64F64::from_num(3i64));
    let t1: I64F64 = ((-I64F64::from_num(4i64)) * t0);
    let t2: I64F64 = (denom * denom);
    let t3: I64F64 = (t1 * t2);
    let t4: I64F64 = pow_int(numer, I64F64::from_num(4i64));
    let t5: I64F64 = (I64F64::from_num(7i64) * t4);
    let t6: I64F64 = (t5 * denom);
    let t7: I64F64 = (t3 + t6);
    let t8: I64F64 = pow_int(numer, I64F64::from_num(5i64));
    let t9: I64F64 = (I64F64::from_num(3i64) * t8);
    let t10: I64F64 = ((-I64F64::ONE) * t9);
    let t11: I64F64 = (t7 + t10);
    t11
}

/// h20(t) numerator (÷ 2·denom^5): accel×T² weight at t=0
#[inline(always)]
pub fn bvh_h20(numer: I64F64, denom: I64F64) -> I64F64 {
    let t0: I64F64 = (numer * numer);
    let t1: I64F64 = pow_int(denom, I64F64::from_num(3i64));
    let t2: I64F64 = (t0 * t1);
    let t3: I64F64 = pow_int(numer, I64F64::from_num(3i64));
    let t4: I64F64 = (I64F64::from_num(3i64) * t3);
    let t5: I64F64 = (denom * denom);
    let t6: I64F64 = (t4 * t5);
    let t7: I64F64 = ((-I64F64::ONE) * t6);
    let t8: I64F64 = (t2 + t7);
    let t9: I64F64 = pow_int(numer, I64F64::from_num(4i64));
    let t10: I64F64 = (I64F64::from_num(3i64) * t9);
    let t11: I64F64 = (t10 * denom);
    let t12: I64F64 = (t8 + t11);
    let t13: I64F64 = pow_int(numer, I64F64::from_num(5i64));
    let t14: I64F64 = ((-I64F64::ONE) * t13);
    let t15: I64F64 = (t12 + t14);
    t15
}

/// h21(t) numerator (÷ 2·denom^5): accel×T² weight at t=1
#[inline(always)]
pub fn bvh_h21(numer: I64F64, denom: I64F64) -> I64F64 {
    let t0: I64F64 = pow_int(numer, I64F64::from_num(3i64));
    let t1: I64F64 = (denom * denom);
    let t2: I64F64 = (t0 * t1);
    let t3: I64F64 = pow_int(numer, I64F64::from_num(4i64));
    let t4: I64F64 = (I64F64::from_num(2i64) * t3);
    let t5: I64F64 = (t4 * denom);
    let t6: I64F64 = ((-I64F64::ONE) * t5);
    let t7: I64F64 = (t2 + t6);
    let t8: I64F64 = pow_int(numer, I64F64::from_num(5i64));
    let t9: I64F64 = (t7 + t8);
    t9
}

#[inline(always)]
pub fn bvh_blend(flag: I64F64, old_val: I64F64, new_val: I64F64) -> I64F64 {
    let t0: I64F64 = ((-I64F64::ONE) * old_val);
    let t1: I64F64 = (new_val + t0);
    let t2: I64F64 = (flag * t1);
    let t3: I64F64 = (old_val + t2);
    t3
}