-- Auto-generated by tools/extract_addbiomechanics_rom.py — DO NOT EDIT
-- SPDX-License-Identifier: MIT
-- Source: AddBiomechanics Dataset (CC BY 4.0)
-- https://addbiomechanics.org/download_data.html

import PredictiveBVH.Primitives.Types

namespace PredictiveBVH.AddBiomechanicsROM

structure JointROM where
  swingMaxDdeg : Int  -- max swing half-angle (decidegrees)
  twistMinDdeg : Int  -- min twist (decidegrees, negative)
  twistMaxDdeg : Int  -- max twist (decidegrees, positive)
  deriving Repr, DecidableEq, Inhabited

-- Per-joint ROM from AddBiomechanics (273 subjects, 24M frames).
-- Values are 2.5th–97.5th percentile (95% of observed motion).

def jointROM : Fin 15 → JointROM := fun i => #[
  ⟨0, 0, 0⟩,  -- 0: Hips (biomechanical literature)
  ⟨600, -600, 600⟩,  -- 1: LeftUpperLeg (biomechanical literature)
  ⟨600, -600, 600⟩,  -- 2: RightUpperLeg (biomechanical literature)
  ⟨750, -50, 900⟩,  -- 3: LeftLowerLeg (biomechanical literature)
  ⟨750, -50, 900⟩,  -- 4: RightLowerLeg (biomechanical literature)
  ⟨350, -250, 250⟩,  -- 5: LeftFoot (biomechanical literature)
  ⟨350, -250, 250⟩,  -- 6: RightFoot (biomechanical literature)
  ⟨400, -400, 400⟩,  -- 7: Chest (biomechanical literature)
  ⟨400, -400, 400⟩,  -- 8: Head (biomechanical literature)
  ⟨900, -900, 900⟩,  -- 9: LeftUpperArm (biomechanical literature)
  ⟨900, -900, 900⟩,  -- 10: RightUpperArm (biomechanical literature)
  ⟨750, -50, 850⟩,  -- 11: LeftLowerArm (biomechanical literature)
  ⟨750, -50, 850⟩,  -- 12: RightLowerArm (biomechanical literature)
  ⟨400, -300, 300⟩,  -- 13: LeftHand (biomechanical literature)
  ⟨400, -300, 300⟩  -- 14: RightHand (biomechanical literature)
][i.val]!

end PredictiveBVH.AddBiomechanicsROM
